"""Shared runtime state for extracted modules. Populated by bot.py at startup."""

bot = None
DATASTORE = None
CONFIG = {}
logger = None
RECONCILE_LOCK = None
MONTHLY_AUDIT_PENDING = False
RITES_LOCK = None
MACHINE_SPIRITS_LOCK = None
ROTATION_LOCK = None
ACTIVITY_STATUS_LOCK = None
PROMOTION_TRACKING_LOCK = None
ARMOR_INTEGRITY_LOCK = None
ARMOR_SCAN_STATE_LOCK = None
INDUCTION_OVERRIDES_LOCK = None
CHALLENGE_PROGRESS_LOCK = None
BLESSING_POOL_LOCK = None
FORGE_POOL_LOCK = None
FORGE_CHRONICLE_LOCK = None
FORGE_OVERRIDE_LOCK = None
LFG_QUEUE_LOCK = None
LFG_ACTIVE_QUEUES = {}
SHUTDOWN_INITIATED = False
LAST_MILESTONE_CHECK_DATE = None
# Librarian / Warp Corruption subsystem
WARP_EXPOSURE_LOCK = None
WARDING_POOL_LOCK = None
LIBRARIUM_CHRONICLE_LOCK = None
LIBRARIUM_OVERRIDE_LOCK = None
# Terminus Kill Log subsystem
TERMINUS_SLAYER_LOCK = None
